"use client";
import { useActionState } from "react";
import { addAccount, addExpense, addManualJournal, createOpeningBalances, type AccountingState } from "./actions";
const initial:AccountingState={success:false,message:""};
function Result({state}:{state:AccountingState}){return state.message?<p role="status" className={`rounded-xl p-3 text-sm ${state.success?"bg-emerald-400/10 text-emerald-300":"bg-red-400/10 text-red-200"}`}>{state.message}</p>:null}
export function AccountForm(){const[s,a,p]=useActionState(addAccount,initial);return <form action={a} className="mt-5 space-y-3"><input className="field" name="code" placeholder="Account code" required/><input className="field" name="name" placeholder="Account name" required/><select className="field" name="account_type"><option value="expense">Expense</option><option value="asset">Asset</option><option value="liability">Liability</option><option value="equity">Equity</option><option value="revenue">Revenue</option></select><button disabled={p} className="rounded-xl bg-emerald-400 px-4 py-3 font-semibold text-slate-950">{p?"Adding…":"Add account"}</button><Result state={s}/></form>}
export function OpeningForm({today}:{today:string}){const[s,a,p]=useActionState(createOpeningBalances,initial);return <form action={a} className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-sm text-slate-300">Opening date<input className="field mt-2" name="opening_date" type="date" defaultValue={today} required/></label><span/><label className="text-sm text-slate-300">Cash<input className="field mt-2" name="cash_amount" type="number" min="0" step="0.01" defaultValue="0" required/></label><label className="text-sm text-slate-300">MGT payable<input className="field mt-2" name="mgt_payable" type="number" min="0" step="0.01" defaultValue="0" required/></label><label className="text-sm text-slate-300">Arcome payable<input className="field mt-2" name="arcome_payable" type="number" min="0" step="0.01" defaultValue="0" required/></label><div className="flex items-end"><button disabled={p} className="rounded-xl bg-emerald-400 px-4 py-3 font-semibold text-slate-950">{p?"Posting…":"Post opening balances"}</button></div><div className="sm:col-span-2"><Result state={s}/></div></form>}
type A={id:string|number;code:string;name:string}; const Options=({accounts}:{accounts:A[]})=><>{accounts.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</>;
export function JournalForm({today,accounts}:{today:string;accounts:A[]}){const[s,a,p]=useActionState(addManualJournal,initial);return <form action={a} className="mt-5 grid gap-3 sm:grid-cols-2"><input className="field" name="entry_date" type="date" defaultValue={today} required/><input className="field" name="reference" placeholder="Reference (optional)"/><input className="field sm:col-span-2" name="description" placeholder="Description" required/><label className="text-sm text-slate-300">Debit account<select className="field mt-2" name="debit_account_id" required><Options accounts={accounts}/></select></label><label className="text-sm text-slate-300">Credit account<select className="field mt-2" name="credit_account_id" required><Options accounts={accounts}/></select></label><input className="field" name="amount" type="number" min="0.01" step="0.01" placeholder="Amount" required/><button disabled={p} className="rounded-xl bg-emerald-400 px-4 py-3 font-semibold text-slate-950">{p?"Posting…":"Post journal"}</button><div className="sm:col-span-2"><Result state={s}/></div></form>}
export function ExpenseForm({today,expenseAccounts,cashAccounts}:{today:string;expenseAccounts:A[];cashAccounts:A[]}){const[s,a,p]=useActionState(addExpense,initial);return <form action={a} className="mt-5 grid gap-3 sm:grid-cols-2"><input className="field" name="expense_date" type="date" defaultValue={today} required/><input className="field" name="reference" placeholder="Reference (optional)"/><input className="field sm:col-span-2" name="description" placeholder="What was paid for?" required/><label className="text-sm text-slate-300">Expense account<select className="field mt-2" name="expense_account_id"><Options accounts={expenseAccounts}/></select></label><label className="text-sm text-slate-300">Paid from<select className="field mt-2" name="paid_from_account_id"><Options accounts={cashAccounts}/></select></label><input className="field" name="amount" type="number" min="0.01" step="0.01" placeholder="Amount" required/><button disabled={p} className="rounded-xl bg-emerald-400 px-4 py-3 font-semibold text-slate-950">{p?"Saving…":"Record expense"}</button><div className="sm:col-span-2"><Result state={s}/></div></form>}

