"use client";
import {useEffect,useState,type ReactNode} from "react";
import {createPortal} from "react-dom";
export type ListColumn={key:string;label:string;align?:"left"|"right"};
export type ListRow={id:string|number;cells:Record<string,ReactNode>;details?:ReactNode};
export function ConfigurableList({title,count,storageKey,columns,defaults,rows,actionLabel,actionContent}:{title:string;count:number;storageKey:string;columns:ListColumn[];defaults:string[];rows:ListRow[];actionLabel?:string;actionContent?:ReactNode}){
  const[selected,setSelected]=useState(defaults),[open,setOpen]=useState(false),[detail,setDetail]=useState<ListRow|null>(null);
  useEffect(()=>{const timer=setTimeout(()=>{try{const value=localStorage.getItem(storageKey);if(value)setSelected(JSON.parse(value))}catch{}},0);return()=>clearTimeout(timer)},[storageKey]);
  const toggle=(key:string)=>setSelected(current=>{const next=current.includes(key)?current.filter(x=>x!==key):[...current,key];localStorage.setItem(storageKey,JSON.stringify(next));return next});
  const modal=(heading:string,content:ReactNode,close:()=>void)=>createPortal(<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-slate-700 bg-slate-900 p-6"><div className="flex justify-between"><h2 className="text-2xl font-bold">{heading}</h2><button onClick={close}>✕</button></div>{content}</section></div>,document.body);
  return <><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="section-title">{title}</h2><p className="mt-1 text-sm text-slate-400">{count} records{rows.some(r=>r.details)?" · Click a row to view":""}</p></div><div className="flex gap-2"><details className="relative"><summary className="cursor-pointer list-none rounded-xl border border-slate-700 px-4 py-2.5 text-sm">⚙ Columns</summary><div className="absolute right-0 z-20 mt-2 w-56 rounded-xl border border-slate-700 bg-slate-900 p-2 shadow-2xl">{columns.map(column=><label key={column.key} className="flex gap-3 rounded-lg px-3 py-2 text-sm hover:bg-slate-800"><input type="checkbox" checked={selected.includes(column.key)} onChange={()=>toggle(column.key)} className="accent-red-500"/>{column.label}</label>)}</div></details>{actionContent&&<button onClick={()=>setOpen(true)} className="rounded-xl bg-emerald-400 px-5 py-2.5 font-semibold text-white">+ {actionLabel}</button>}</div></div>{rows.length===0?<div className="mt-5 rounded-xl border border-dashed border-slate-700 p-10 text-center text-slate-400">No records to display.</div>:<div className="mt-5 overflow-x-auto rounded-xl border border-slate-800"><table className="data-table"><thead><tr>{columns.filter(c=>selected.includes(c.key)).map(c=><th key={c.key} className={c.align==="right"?"text-right":""}>{c.label}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id} onClick={()=>row.details&&setDetail(row)} className={row.details?"cursor-pointer":""}>{columns.filter(c=>selected.includes(c.key)).map(c=><td key={c.key} className={c.align==="right"?"text-right":""}>{row.cells[c.key]??"—"}</td>)}</tr>)}</tbody></table></div>}{open&&actionContent&&modal(actionLabel??"New record",actionContent,()=>setOpen(false))}{detail?.details&&modal(`${title} details`,detail.details,()=>setDetail(null))}</>;
}
