"use client";

import { FormEvent, useMemo, useState } from "react";

type Message={role:"user"|"assistant";text:string};
const suggestions=["Summarize delivery performance for this period.","Which drivers delivered the most orders?","Show cash differences that need attention.","Summarize supplier invoices and payments.","Give me an accounting overview."];

export function AssistantChat(){
  const today=new Date().toISOString().slice(0,10),month=`${today.slice(0,7)}-01`;
  const[from,setFrom]=useState(month),[to,setTo]=useState(today),[question,setQuestion]=useState(""),[messages,setMessages]=useState<Message[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const canSend=useMemo(()=>question.trim().length>=3&&!busy,[question,busy]);
  async function submit(event:FormEvent){event.preventDefault();if(!canSend)return;const text=question.trim();setQuestion("");setError("");setMessages(current=>[...current,{role:"user",text}]);setBusy(true);try{const response=await fetch("/api/assistant",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({question:text,from,to})});const result=await response.json();if(!response.ok)throw new Error(result.error||"The assistant could not answer.");setMessages(current=>[...current,{role:"assistant",text:result.answer}])}catch(value){setError(value instanceof Error?value.message:"The assistant could not answer.")}finally{setBusy(false)}}
  return <div className="mt-8 grid gap-6 lg:grid-cols-[280px_1fr]">
    <aside className="surface-card h-fit"><h2 className="section-title">Report period</h2><label className="mt-5 block text-sm text-slate-400">From<input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100"/></label><label className="mt-4 block text-sm text-slate-400">To<input type="date" value={to} onChange={e=>setTo(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100"/></label><div className="mt-6 border-t border-slate-800 pt-5"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Try asking</p><div className="mt-3 space-y-2">{suggestions.map(item=><button key={item} type="button" onClick={()=>setQuestion(item)} className="w-full rounded-xl border border-slate-800 px-3 py-2 text-left text-sm text-slate-300 hover:border-emerald-400/40 hover:text-emerald-300">{item}</button>)}</div></div></aside>
    <section className="surface-card flex min-h-[620px] flex-col"><div className="flex items-center justify-between border-b border-slate-800 pb-4"><div><h2 className="section-title">Ask SRT</h2><p className="mt-1 text-sm text-slate-400">Answers use live data for the selected dates.</p></div><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs font-semibold text-emerald-300">READ ONLY</span></div>
      <div className="flex-1 space-y-4 overflow-y-auto py-6">{messages.length===0?<div className="mx-auto mt-16 max-w-lg text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-emerald-400/10 text-2xl text-emerald-300">✦</div><h3 className="mt-5 text-xl font-semibold">What would you like to know?</h3><p className="mt-2 text-slate-400">Choose a suggestion or ask a question about SRT operations and accounting.</p></div>:messages.map((message,index)=><div key={index} className={`max-w-3xl rounded-2xl px-4 py-3 whitespace-pre-wrap ${message.role==="user"?"ml-auto bg-emerald-400 text-slate-950":"border border-slate-800 bg-slate-950 text-slate-200"}`}>{message.text}</div>)}{busy&&<div className="w-fit rounded-2xl border border-slate-800 bg-slate-950 px-4 py-3 text-slate-400">Reviewing SRT data…</div>}{error&&<p className="rounded-xl bg-red-400/10 p-4 text-red-200">{error}</p>}</div>
      <form onSubmit={submit} className="flex gap-3 border-t border-slate-800 pt-4"><textarea value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();e.currentTarget.form?.requestSubmit()}}} rows={2} placeholder="Ask about trips, cash, expenses, suppliers, payroll…" className="min-h-14 flex-1 resize-none rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-slate-100 outline-none focus:border-emerald-400"/><button disabled={!canSend} className="rounded-xl bg-emerald-400 px-5 font-semibold text-slate-950 disabled:cursor-not-allowed disabled:opacity-40">Send</button></form>
      <p className="mt-3 text-xs text-slate-500">AI answers can be incorrect. Verify important totals against the application reports.</p>
    </section>
  </div>
}
