"use client";
import { useActionState, useState } from "react";
import { postInvoice, postPayment, type SupplierState } from "./actions";
const initial: SupplierState = { success: false, message: "" };
type Option = { id: string | number; code?: string; name: string; payable_account_id?: string | number | null; default_expense_account_id?: string | number | null };
const Result = ({ state }: { state: SupplierState }) => state.message ? <p className={state.success ? "text-emerald-300" : "text-red-200"}>{state.message}</p> : null;
const Options = ({ items }: { items: Option[] }) => <>{items.map(item => <option key={item.id} value={item.id}>{item.code ? `${item.code} — ` : ""}{item.name}</option>)}</>;
const Field = ({ label, children }: { label: string; children: React.ReactNode }) => <label className="block text-sm font-medium text-slate-300">{label}<div className="mt-2">{children}</div></label>;

export function InvoiceForm({ suppliers, expenses, payables = [], today }: { suppliers: Option[]; expenses: Option[]; payables?: Option[]; today: string }) {
  const [state, action, pending] = useActionState(postInvoice, initial), [payable, setPayable] = useState(""), [expense, setExpense] = useState("");
  function chooseSupplier(id: string) { const supplier = suppliers.find(item => String(item.id) === id); setPayable(supplier?.payable_account_id ? String(supplier.payable_account_id) : ""); setExpense(supplier?.default_expense_account_id ? String(supplier.default_expense_account_id) : ""); }
  return <form action={action} className="mt-5 grid gap-4 sm:grid-cols-2">
    <Field label="Supplier"><select className="field" name="supplier_id" required defaultValue="" onChange={event => chooseSupplier(event.target.value)}><option value="" disabled>{suppliers.length ? "Select supplier" : "No active suppliers"}</option><Options items={suppliers} /></select></Field>
    <Field label="Supplier payable account"><select className="field" name="payable_account_id" required value={payable} onChange={event => setPayable(event.target.value)}><option value="" disabled>{payables.length ? "Select liability account" : "No active liability accounts"}</option><Options items={payables} /></select></Field>
    <Field label="Supplier invoice number"><input className="field" name="invoice_number" placeholder="Example: INV-001" required /></Field><Field label="Invoice date"><input className="field" name="invoice_date" type="date" defaultValue={today} /></Field>
    <Field label="Expense account"><select className="field" name="expense_account_id" required value={expense} onChange={event => setExpense(event.target.value)}><option value="" disabled>{expenses.length ? "Select expense account" : "No active expense accounts"}</option><Options items={expenses} /></select></Field>
    <Field label="Amount"><input className="field" name="amount" type="number" min="0.01" step="0.01" placeholder="0.00" required /></Field><Field label="Reference (optional)"><input className="field" name="reference" placeholder="Reference" /></Field><div className="sm:col-span-2"><Field label="Description"><input className="field" name="description" placeholder="Service or charge description" required /></Field></div>
    {(!suppliers.length || !expenses.length || !payables.length) && <p className="rounded-xl bg-amber-400/10 p-3 text-sm text-amber-200 sm:col-span-2">Add or activate the required supplier, expense, and liability accounts before recording an invoice.</p>}
    <button disabled={pending || !suppliers.length || !expenses.length || !payables.length} className="rounded-xl bg-emerald-400 px-4 py-3 font-semibold text-slate-950 disabled:cursor-not-allowed disabled:opacity-50">{pending ? "Posting…" : "Post supplier invoice"}</button><Result state={state} />
  </form>;
}

export function PaymentForm({ suppliers, cashAccounts, today }: { suppliers: Option[]; cashAccounts: Option[]; today: string }) { const [state, action, pending] = useActionState(postPayment, initial); return <form action={action} className="mt-5 grid gap-3 sm:grid-cols-2"><select className="field" name="supplier_id"><Options items={suppliers} /></select><input className="field" name="payment_date" type="date" defaultValue={today} /><select className="field" name="cash_account_id"><Options items={cashAccounts} /></select><input className="field" name="amount" type="number" min="0.01" step="0.01" placeholder="Amount" required /><select className="field" name="payment_method"><option value="cash">Cash</option><option value="bank">Bank</option><option value="whish">Whish</option><option value="other">Other</option></select><input className="field" name="reference" placeholder="Reference (optional)" /><input className="field sm:col-span-2" name="notes" placeholder="Notes (optional)" /><button disabled={pending} className="rounded-xl bg-emerald-400 px-4 py-3 font-semibold text-slate-950">{pending ? "Posting…" : "Post supplier payment"}</button><Result state={state} /></form>; }
