import Link from "next/link";
import { DateFilter } from "@/components/date-filter";
import { PageTabs } from "@/components/page-tabs";
import { createAdminClient } from "@/lib/supabase/admin";
import { dateInTimeZone,formatCurrency,getAppSettings } from "@/lib/settings";
import { SupplierForm } from "./supplier-form";
export const dynamic="force-dynamic";
type Params={view?:string;supplier?:string;from?:string;to?:string};
export default async function SuppliersPage({searchParams}:{searchParams:Promise<Params>}){
  const p=await searchParams,view=["overview","new","statement"].includes(p.view??"")?p.view!:"overview",settings=await getAppSettings(),today=dateInTimeZone(settings.timezone),from=/^\d{4}-\d{2}-\d{2}$/.test(p.from??"")?p.from!:`${today.slice(0,7)}-01`,to=/^\d{4}-\d{2}-\d{2}$/.test(p.to??"")?p.to!:today,s=await createAdminClient();
  const[suppliers,accounts,balances,invoices,payments]=await Promise.all([
    s.from("suppliers").select("id,code,name,payable_account_id,default_expense_account_id,phone,email,notes,is_active").order("name"),s.from("accounts").select("id,code,name,account_type,is_active").eq("is_active",true).order("code"),s.from("account_balances").select("id,balance"),s.from("supplier_invoices").select("id,invoice_number,supplier_id,invoice_date,amount,description,reference,status").gte("invoice_date",from).lte("invoice_date",to).order("invoice_date"),s.from("supplier_payments").select("id,payment_number,supplier_id,payment_date,amount,reference,status").gte("payment_date",from).lte("payment_date",to).order("payment_date")
  ]);
  const supplierRows=suppliers.data??[],payables=(accounts.data??[]).filter(x=>x.account_type==="liability"),expenses=(accounts.data??[]).filter(x=>x.account_type==="expense"),balanceMap=new Map((balances.data??[]).map(x=>[String(x.id),Number(x.balance)])),selected=supplierRows.find(x=>String(x.id)===p.supplier)??supplierRows[0];
  const selectedInvoices=(invoices.data??[]).filter(x=>x.status!=="voided"&&String(x.supplier_id)===String(selected?.id)),selectedPayments=(payments.data??[]).filter(x=>x.status!=="voided"&&String(x.supplier_id)===String(selected?.id)),activity=[...selectedInvoices.map(x=>({id:`i-${x.id}`,date:x.invoice_date,document:x.invoice_number,type:"Invoice",description:x.description,debit:0,credit:Number(x.amount)})),...selectedPayments.map(x=>({id:`p-${x.id}`,date:x.payment_date,document:x.payment_number,type:"Payment",description:x.reference??"Supplier payment",debit:Number(x.amount),credit:0}))].sort((a,b)=>a.date.localeCompare(b.date));
  return <main className="min-h-screen bg-slate-950 px-6 py-10 text-slate-100"><div className="mx-auto max-w-7xl"><p className="eyebrow">ACCOUNTING</p><h1 className="page-title">Suppliers</h1><p className="page-lead">Manage supplier accounts, invoices, payments, and balances from one workspace.</p><div className="mt-8"><PageTabs current={view} items={[{key:"overview",label:"Overview",href:"/accounting/suppliers"},{key:"new",label:"New supplier",href:"/accounting/suppliers?view=new"},{key:"statement",label:"Supplier statements",href:"/accounting/suppliers?view=statement"}]}/></div>
  {view==="overview"&&<section className="mt-6 grid gap-4 lg:grid-cols-2">{supplierRows.map(x=><article key={x.id} className="surface-card"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-emerald-300">{x.code}</p><h2 className="mt-1 text-xl font-bold">{x.name}</h2></div><span className={`rounded-full px-3 py-1 text-xs ${x.is_active?"bg-emerald-400/10 text-emerald-300":"bg-slate-700 text-slate-300"}`}>{x.is_active?"Active":"Inactive"}</span></div><p className="mt-5 text-sm text-slate-400">Amount payable</p><p className="mt-1 text-3xl font-bold text-amber-300">{formatCurrency(balanceMap.get(String(x.payable_account_id))??0,settings.currency_code)}</p><div className="mt-5 flex gap-3"><Link className="rounded-xl bg-emerald-400 px-4 py-2 font-semibold text-slate-950" href={`/accounting/suppliers?view=statement&supplier=${x.id}`}>View statement</Link><details className="group"><summary className="cursor-pointer rounded-xl border border-slate-700 px-4 py-2">Edit</summary><div className="mt-4 border-t border-slate-800 pt-1"><SupplierForm supplier={x} payables={payables} expenses={expenses}/></div></details></div></article>)}</section>}
  {view==="new"&&<section className="surface-card mt-6 max-w-3xl"><h2 className="section-title">Create supplier</h2><p className="mt-1 text-sm text-slate-400">Assign one liability account and one default expense account.</p><SupplierForm payables={payables} expenses={expenses}/></section>}
  {view==="statement"&&<><div className="mt-6 flex flex-wrap gap-2">{supplierRows.map(x=><Link key={x.id} href={`/accounting/suppliers?view=statement&supplier=${x.id}&from=${from}&to=${to}`} className={`rounded-xl px-4 py-2 ${String(x.id)===String(selected?.id)?"bg-emerald-400 font-semibold text-slate-950":"border border-slate-700"}`}>{x.name}</Link>)}</div><DateFilter from={from} to={to} basePath="/accounting/suppliers?view=statement" extra={{view:"statement",...(selected?{supplier:String(selected.id)}:{})}}/><section className="surface-card mt-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-slate-400">Supplier statement</p><h2 className="mt-1 text-2xl font-bold">{selected?.name??"No supplier"}</h2></div><div className="text-right"><p className="text-sm text-slate-400">Current payable balance</p><p className="mt-1 text-2xl font-bold text-amber-300">{formatCurrency(balanceMap.get(String(selected?.payable_account_id))??0,settings.currency_code)}</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><Metric label="Invoices in period" value={formatCurrency(selectedInvoices.reduce((sum,x)=>sum+Number(x.amount),0),settings.currency_code)}/><Metric label="Payments in period" value={formatCurrency(selectedPayments.reduce((sum,x)=>sum+Number(x.amount),0),settings.currency_code)}/><Metric label="Net movement" value={formatCurrency(selectedInvoices.reduce((sum,x)=>sum+Number(x.amount),0)-selectedPayments.reduce((sum,x)=>sum+Number(x.amount),0),settings.currency_code)}/></div><div className="mt-6 overflow-x-auto"><table className="data-table"><thead><tr><th>Date</th><th>Document</th><th>Type</th><th>Description</th><th className="text-right">Payment</th><th className="text-right">Invoice</th></tr></thead><tbody>{activity.map(x=><tr key={x.id}><td>{x.date}</td><td className="text-emerald-300">{x.document}</td><td>{x.type}</td><td>{x.description}</td><td className="text-right">{x.debit?formatCurrency(x.debit,settings.currency_code):"—"}</td><td className="text-right">{x.credit?formatCurrency(x.credit,settings.currency_code):"—"}</td></tr>)}{!activity.length&&<tr><td colSpan={6} className="py-8 text-center text-slate-400">No supplier activity for these dates.</td></tr>}</tbody></table></div></section></>}
  </div></main>;
}
function Metric({label,value}:{label:string;value:string}){return <article className="metric-card"><p>{label}</p><strong>{value}</strong></article>}
