-- SRT accounting, suppliers, expenses, employees, compensation and payroll.
-- Additive migration: existing drivers, trips, regions, vehicles and trip_details
-- are not replaced or rewritten.

create extension if not exists btree_gist;

create table public.accounts (
    id bigint generated by default as identity primary key,
    code text not null unique check (btrim(code) <> ''),
    name text not null check (btrim(name) <> ''),
    account_type text not null check (account_type in ('asset','liability','equity','revenue','expense')),
    normal_balance text not null check (normal_balance in ('debit','credit')),
    parent_id bigint references public.accounts(id),
    is_control_account boolean not null default false,
    is_system boolean not null default false,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (parent_id is null or parent_id <> id)
);

create table public.journal_entries (
    id bigint generated by default as identity primary key,
    entry_number text not null unique,
    entry_date date not null,
    description text not null check (btrim(description) <> ''),
    reference text,
    source_type text not null default 'manual',
    source_id text,
    status text not null default 'draft' check (status in ('draft','posted','voided')),
    posted_at timestamptz,
    posted_by uuid references auth.users(id),
    reversal_of_id bigint references public.journal_entries(id),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check ((status = 'posted' and posted_at is not null) or status <> 'posted')
);

create unique index journal_entries_source_unique
    on public.journal_entries(source_type, source_id)
    where source_id is not null and status <> 'voided';

create table public.journal_lines (
    id bigint generated by default as identity primary key,
    journal_entry_id bigint not null references public.journal_entries(id) on delete cascade,
    line_number integer not null check (line_number > 0),
    account_id bigint not null references public.accounts(id),
    description text,
    debit numeric(14,2) not null default 0 check (debit >= 0),
    credit numeric(14,2) not null default 0 check (credit >= 0),
    created_at timestamptz not null default now(),
    unique (journal_entry_id, line_number),
    check ((debit > 0 and credit = 0) or (credit > 0 and debit = 0))
);

create index journal_lines_account_idx on public.journal_lines(account_id);
create index journal_entries_date_idx on public.journal_entries(entry_date, id);

create table public.suppliers (
    id bigint generated by default as identity primary key,
    code text not null unique,
    name text not null unique,
    payable_account_id bigint not null references public.accounts(id),
    default_expense_account_id bigint references public.accounts(id),
    phone text,
    email text,
    notes text,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.supplier_invoices (
    id bigint generated by default as identity primary key,
    invoice_number text not null,
    supplier_id bigint not null references public.suppliers(id),
    invoice_date date not null,
    due_date date,
    expense_account_id bigint not null references public.accounts(id),
    amount numeric(14,2) not null check (amount > 0),
    description text not null,
    reference text,
    status text not null default 'draft' check (status in ('draft','posted','voided')),
    journal_entry_id bigint unique references public.journal_entries(id),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (supplier_id, invoice_number)
);

create table public.supplier_payments (
    id bigint generated by default as identity primary key,
    payment_number text not null unique,
    supplier_id bigint not null references public.suppliers(id),
    payment_date date not null,
    cash_account_id bigint not null references public.accounts(id),
    amount numeric(14,2) not null check (amount > 0),
    payment_method text not null default 'cash',
    reference text,
    notes text,
    status text not null default 'draft' check (status in ('draft','posted','voided')),
    journal_entry_id bigint unique references public.journal_entries(id),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.expense_transactions (
    id bigint generated by default as identity primary key,
    expense_number text not null unique,
    expense_date date not null,
    expense_account_id bigint not null references public.accounts(id),
    paid_from_account_id bigint not null references public.accounts(id),
    amount numeric(14,2) not null check (amount > 0),
    description text not null,
    reference text,
    source_type text not null default 'manual_expense',
    source_id text,
    status text not null default 'draft' check (status in ('draft','posted','voided')),
    journal_entry_id bigint unique references public.journal_entries(id),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index expense_transactions_source_unique
    on public.expense_transactions(source_type, source_id)
    where source_id is not null and status <> 'voided';

create table public.positions (
    id bigint generated by default as identity primary key,
    name text not null unique check (btrim(name) <> ''),
    description text,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create table public.employees (
    id bigint generated by default as identity primary key,
    employee_number text unique,
    name text not null check (btrim(name) <> ''),
    position_id bigint not null references public.positions(id),
    phone text,
    address text,
    emergency_contact_name text,
    emergency_contact_phone text,
    id_number text,
    start_date date,
    end_date date,
    notes text,
    status text not null default 'active' check (status in ('active','inactive')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (end_date is null or start_date is null or end_date >= start_date)
);

create unique index employees_id_number_unique
    on public.employees(id_number) where id_number is not null and btrim(id_number) <> '';

create table public.employee_salary_history (
    id bigint generated by default as identity primary key,
    employee_id bigint not null references public.employees(id),
    monthly_salary numeric(14,2) not null check (monthly_salary >= 0),
    effective_from date not null,
    effective_to date,
    reason text,
    created_at timestamptz not null default now(),
    check (effective_to is null or effective_to >= effective_from),
    exclude using gist (
        employee_id with =,
        daterange(effective_from, coalesce(effective_to + 1, 'infinity'::date), '[)') with &&
    )
);

create table public.commission_schemes (
    id bigint generated by default as identity primary key,
    name text not null unique,
    description text,
    calculation_method text not null default 'final_tier_rate'
        check (calculation_method in ('final_tier_rate')),
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create table public.commission_scheme_versions (
    id bigint generated by default as identity primary key,
    commission_scheme_id bigint not null references public.commission_schemes(id),
    version_number integer not null check (version_number > 0),
    effective_from date not null,
    effective_to date,
    notes text,
    created_at timestamptz not null default now(),
    unique (commission_scheme_id, version_number),
    check (effective_to is null or effective_to >= effective_from),
    exclude using gist (
        commission_scheme_id with =,
        daterange(effective_from, coalesce(effective_to + 1, 'infinity'::date), '[)') with &&
    )
);

create table public.commission_tiers (
    id bigint generated by default as identity primary key,
    commission_scheme_version_id bigint not null references public.commission_scheme_versions(id) on delete cascade,
    minimum_orders integer not null check (minimum_orders >= 0),
    maximum_orders integer check (maximum_orders is null or maximum_orders >= minimum_orders),
    rate_per_order numeric(14,4) not null check (rate_per_order >= 0),
    created_at timestamptz not null default now(),
    unique (commission_scheme_version_id, minimum_orders)
);

create table public.driver_compensation_history (
    id bigint generated by default as identity primary key,
    driver_id uuid not null references public.drivers(id),
    monthly_salary numeric(14,2) not null check (monthly_salary >= 0),
    commission_scheme_id bigint references public.commission_schemes(id),
    effective_from date not null,
    effective_to date,
    reason text,
    created_at timestamptz not null default now(),
    check (effective_to is null or effective_to >= effective_from),
    exclude using gist (
        driver_id with =,
        daterange(effective_from, coalesce(effective_to + 1, 'infinity'::date), '[)') with &&
    )
);

create table public.payroll_runs (
    id bigint generated by default as identity primary key,
    payroll_number text not null unique,
    period_start date not null,
    period_end date not null,
    payment_date date,
    status text not null default 'draft' check (status in ('draft','approved','paid')),
    notes text,
    approved_at timestamptz,
    approved_by uuid references auth.users(id),
    paid_at timestamptz,
    paid_by uuid references auth.users(id),
    approval_journal_entry_id bigint unique references public.journal_entries(id),
    payment_journal_entry_id bigint unique references public.journal_entries(id),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (period_end >= period_start),
    check (status = 'draft' or approved_at is not null),
    check (status <> 'paid' or (paid_at is not null and payment_date is not null))
);

create table public.payroll_items (
    id bigint generated by default as identity primary key,
    payroll_run_id bigint not null references public.payroll_runs(id) on delete cascade,
    worker_type text not null check (worker_type in ('employee','driver')),
    employee_id bigint references public.employees(id),
    driver_id uuid references public.drivers(id),
    worker_name_snapshot text not null,
    position_snapshot text,
    fixed_salary_snapshot numeric(14,2) not null default 0 check (fixed_salary_snapshot >= 0),
    delivered_orders_snapshot integer not null default 0 check (delivered_orders_snapshot >= 0),
    commission_scheme_name_snapshot text,
    commission_version_snapshot integer,
    tier_minimum_snapshot integer,
    tier_maximum_snapshot integer,
    commission_rate_snapshot numeric(14,4) not null default 0 check (commission_rate_snapshot >= 0),
    commission_amount_snapshot numeric(14,2) not null default 0 check (commission_amount_snapshot >= 0),
    deductions numeric(14,2) not null default 0 check (deductions >= 0),
    additions numeric(14,2) not null default 0 check (additions >= 0),
    gross_pay numeric(14,2) generated always as
        (fixed_salary_snapshot + commission_amount_snapshot + additions) stored,
    net_pay numeric(14,2) generated always as
        (fixed_salary_snapshot + commission_amount_snapshot + additions - deductions) stored,
    notes text,
    created_at timestamptz not null default now(),
    check (
        (worker_type = 'employee' and employee_id is not null and driver_id is null) or
        (worker_type = 'driver' and driver_id is not null and employee_id is null)
    ),
    unique nulls not distinct (payroll_run_id, employee_id, driver_id)
);

-- Core chart and supplier masters. Names/rates remain editable; system accounts
-- cannot be deleted because posted records reference them.
insert into public.accounts (code, name, account_type, normal_balance, is_control_account, is_system)
values
    ('1000', 'Cash', 'asset', 'debit', true, true),
    ('1100', 'Trip Receivable', 'asset', 'debit', true, true),
    ('2001', 'MGT Payable', 'liability', 'credit', true, true),
    ('2002', 'Arcome Safety Logistics Payable', 'liability', 'credit', true, true),
    ('2100', 'Payroll Payable', 'liability', 'credit', true, true),
    ('3000', 'Funder Capital / Contributions', 'equity', 'credit', false, true),
    ('3100', 'Opening Balance Equity', 'equity', 'credit', false, true),
    ('5000', 'Trip Fuel Expense', 'expense', 'debit', false, true),
    ('5010', 'Supplier Service Expense', 'expense', 'debit', false, true),
    ('5020', 'Salary Expense', 'expense', 'debit', false, true),
    ('5030', 'Driver Commission Expense', 'expense', 'debit', false, true)
on conflict (code) do nothing;

insert into public.suppliers (code, name, payable_account_id, default_expense_account_id)
select 'MGT', 'MGT', p.id, e.id from public.accounts p cross join public.accounts e
where p.code = '2001' and e.code = '5010'
on conflict (code) do nothing;

insert into public.suppliers (code, name, payable_account_id, default_expense_account_id)
select 'ARCOME', 'Arcome Safety Logistics', p.id, e.id from public.accounts p cross join public.accounts e
where p.code = '2002' and e.code = '5010'
on conflict (code) do nothing;

insert into public.positions (name) values
    ('Customer Service'), ('Stock Manager'), ('Stock Keeper')
on conflict (name) do nothing;

-- Sequence-backed document numbers are generated in the database so concurrent
-- users cannot create duplicates.
create sequence if not exists public.journal_entry_number_seq;
create sequence if not exists public.expense_number_seq;
create sequence if not exists public.supplier_payment_number_seq;
create sequence if not exists public.payroll_number_seq;

create or replace function public.next_document_number(prefix text, sequence_name regclass)
returns text language plpgsql volatile set search_path = public as $$
declare next_value bigint;
begin
    execute format('select nextval(%L)', sequence_name::text) into next_value;
    return prefix || '-' || lpad(next_value::text, 6, '0');
end;
$$;

create or replace function public.validate_commission_tiers(version_id bigint)
returns void language plpgsql set search_path = public as $$
declare invalid_count integer;
begin
    with ordered as (
        select minimum_orders, maximum_orders,
               lag(maximum_orders) over (order by minimum_orders) previous_max,
               lead(minimum_orders) over (order by minimum_orders) next_min
        from public.commission_tiers
        where commission_scheme_version_id = version_id
    )
    select count(*) into invalid_count from ordered
    where minimum_orders <> 0 and previous_max is null
       or previous_max is not null and minimum_orders <> previous_max + 1
       or maximum_orders is null and next_min is not null;

    if invalid_count > 0 or not exists (
        select 1 from public.commission_tiers
        where commission_scheme_version_id = version_id and maximum_orders is null
    ) then
        raise exception 'Commission tiers must start at 0, be continuous, not overlap, and finish with no maximum.';
    end if;
end;
$$;

create or replace function public.post_journal(entry_id bigint)
returns void language plpgsql security definer set search_path = public as $$
declare debit_total numeric(14,2); credit_total numeric(14,2); current_status text;
begin
    select status into current_status from public.journal_entries where id = entry_id for update;
    if current_status is null then raise exception 'Journal entry not found.'; end if;
    if current_status <> 'draft' then raise exception 'Only draft journals can be posted.'; end if;
    select coalesce(sum(debit),0), coalesce(sum(credit),0)
      into debit_total, credit_total from public.journal_lines where journal_entry_id = entry_id;
    if debit_total <= 0 or debit_total <> credit_total then
        raise exception 'Journal entry must be balanced and greater than zero.';
    end if;
    update public.journal_entries set status='posted', posted_at=now(), posted_by=auth.uid(), updated_at=now()
    where id=entry_id;
end;
$$;

create or replace function public.guard_posted_journal_entry()
returns trigger language plpgsql as $$
begin
    if old.status = 'posted' then
        raise exception 'Posted journal entries are immutable; create a reversal instead.';
    end if;
    return coalesce(new,old);
end;
$$;

create or replace function public.guard_posted_journal_line()
returns trigger language plpgsql as $$
declare target_entry_id bigint;
begin
    target_entry_id := case when tg_op='DELETE' then old.journal_entry_id else new.journal_entry_id end;
    if exists (
        select 1 from public.journal_entries where id=target_entry_id and status='posted'
    ) then
        raise exception 'Lines of a posted journal entry are immutable.';
    end if;
    return coalesce(new,old);
end;
$$;

create trigger guard_posted_journal_entry before update or delete on public.journal_entries
for each row execute function public.guard_posted_journal_entry();
create trigger guard_posted_journal_lines before update or delete on public.journal_lines
for each row execute function public.guard_posted_journal_line();

create or replace function public.guard_locked_payroll_run()
returns trigger language plpgsql as $$
begin
    if old.status in ('approved','paid') then
        raise exception 'Approved or paid payroll is immutable.';
    end if;
    return coalesce(new,old);
end;
$$;

create or replace function public.guard_locked_payroll_item()
returns trigger language plpgsql as $$
declare target_run_id bigint;
begin
    target_run_id := case when tg_op='DELETE' then old.payroll_run_id else new.payroll_run_id end;
    if exists (
        select 1 from public.payroll_runs where id=target_run_id and status in ('approved','paid')
    ) then raise exception 'Approved payroll snapshots are immutable.'; end if;
    return coalesce(new,old);
end;
$$;

create trigger guard_locked_payroll_run before update or delete on public.payroll_runs
for each row execute function public.guard_locked_payroll_run();
create trigger guard_locked_payroll_items before update or delete on public.payroll_items
for each row execute function public.guard_locked_payroll_item();

create view public.general_ledger as
select je.id journal_entry_id, je.entry_number, je.entry_date, je.description entry_description,
       je.reference, je.source_type, je.source_id, jl.line_number, a.id account_id,
       a.code account_code, a.name account_name, a.account_type, jl.description line_description,
       jl.debit, jl.credit
from public.journal_entries je
join public.journal_lines jl on jl.journal_entry_id=je.id
join public.accounts a on a.id=jl.account_id
where je.status='posted';

create view public.account_balances as
select a.id, a.code, a.name, a.account_type, a.normal_balance,
       coalesce(sum(gl.debit),0)::numeric(14,2) total_debit,
       coalesce(sum(gl.credit),0)::numeric(14,2) total_credit,
       case when a.normal_balance='debit'
            then (coalesce(sum(gl.debit),0)-coalesce(sum(gl.credit),0))::numeric(14,2)
            else (coalesce(sum(gl.credit),0)-coalesce(sum(gl.debit),0))::numeric(14,2) end balance
from public.accounts a left join public.general_ledger gl on gl.account_id=a.id
group by a.id, a.code, a.name, a.account_type, a.normal_balance;

-- Opening balances: one balanced, posted journal created from simple inputs.
create or replace function public.create_opening_balances(
    opening_date date, cash_amount numeric, mgt_payable numeric, arcome_payable numeric
) returns bigint language plpgsql security definer set search_path=public as $$
declare entry_id bigint; cash_id bigint; mgt_id bigint; arcome_id bigint; equity_id bigint; difference numeric;
begin
    if exists(select 1 from public.journal_entries where source_type='opening_balance' and status<>'voided') then
        raise exception 'Opening balances have already been created.';
    end if;
    if least(cash_amount,mgt_payable,arcome_payable) < 0 then raise exception 'Opening balances cannot be negative.'; end if;
    select id into cash_id from public.accounts where code='1000';
    select id into mgt_id from public.accounts where code='2001';
    select id into arcome_id from public.accounts where code='2002';
    select id into equity_id from public.accounts where code='3100';
    insert into public.journal_entries(entry_number,entry_date,description,source_type,source_id)
    values(public.next_document_number('JE','public.journal_entry_number_seq'),opening_date,'Opening balances','opening_balance','initial') returning id into entry_id;
    if cash_amount>0 then insert into public.journal_lines values(default,entry_id,1,cash_id,'Opening cash',cash_amount,0,default); end if;
    if mgt_payable>0 then insert into public.journal_lines values(default,entry_id,2,mgt_id,'Opening MGT payable',0,mgt_payable,default); end if;
    if arcome_payable>0 then insert into public.journal_lines values(default,entry_id,3,arcome_id,'Opening Arcome payable',0,arcome_payable,default); end if;
    difference := mgt_payable + arcome_payable - cash_amount;
    if difference>0 then insert into public.journal_lines values(default,entry_id,4,equity_id,'Opening balance equity',difference,0,default);
    elsif difference<0 then insert into public.journal_lines values(default,entry_id,4,equity_id,'Opening balance equity',0,-difference,default); end if;
    perform public.post_journal(entry_id); return entry_id;
end;
$$;

-- RLS follows the existing private single-user authorization model.
do $$ declare table_name text; begin
    foreach table_name in array array['accounts','journal_entries','journal_lines','suppliers','supplier_invoices','supplier_payments','expense_transactions','positions','employees','employee_salary_history','commission_schemes','commission_scheme_versions','commission_tiers','driver_compensation_history','payroll_runs','payroll_items'] loop
        execute format('alter table public.%I enable row level security',table_name);
        execute format('grant select,insert,update,delete on public.%I to authenticated',table_name);
        execute format('create policy "SRT authorized access" on public.%I for all to authenticated using ((select public.is_srt_authorized())) with check ((select public.is_srt_authorized()))',table_name);
    end loop;
end $$;

grant usage, select on all sequences in schema public to authenticated;
grant select on public.general_ledger, public.account_balances to authenticated;
grant execute on function public.post_journal(bigint) to authenticated;
grant execute on function public.create_opening_balances(date,numeric,numeric,numeric) to authenticated;
grant execute on function public.validate_commission_tiers(bigint) to authenticated;
