"use client";
import { useActionState,useState } from "react";
import { addDriverCompensation,addSchemeVersion,type CState } from "./actions";
const i:CState={success:false,message:""};
const R=({s}:{s:CState})=>s.message?<p className={s.success?"text-emerald-300":"text-red-200"}>{s.message}</p>:null;
type O={id:string|number;name:string};
type Tier={key:number;name:string;color:string;min:string;max:string;rate:string};
const defaults:Tier[]=[{key:1,name:"Starter",color:"#c47a32",min:"0",max:"100",rate:"0.50"},{key:2,name:"Silver",color:"#aeb4bd",min:"101",max:"200",rate:"0.60"},{key:3,name:"Gold",color:"#f4c20d",min:"201",max:"300",rate:"0.70"},{key:4,name:"Diamond",color:"#67d7ed",min:"301",max:"",rate:"0.80"}];
export function SchemeForm({today}:{today:string}){const[s,a,p]=useActionState(addSchemeVersion,i),[tiers,setTiers]=useState(defaults);const change=(key:number,field:keyof Omit<Tier,"key">,value:string)=>setTiers(current=>current.map(t=>t.key===key?{...t,[field]:value}:t));return <form action={a} className="mt-5 space-y-4"><input className="field" name="name" placeholder="Scheme name, e.g. Standard Drivers" required/><label className="text-sm text-slate-300">Effective from<input className="field mt-2" name="effective_from" type="date" defaultValue={today}/></label><div><div className="mb-3 flex items-center justify-between"><div><p className="text-sm font-medium text-slate-300">Commission badges</p><p className="text-xs text-slate-500">Leave the final maximum empty for unlimited orders.</p></div><button type="button" onClick={()=>setTiers(x=>[...x,{key:Date.now(),name:"New badge",color:"#ef4444",min:"",max:"",rate:""}])} className="rounded-lg border border-slate-700 px-3 py-2 text-sm hover:bg-slate-800">+ Add badge</button></div><div className="space-y-3">{tiers.map((t,index)=><div key={t.key} className="rounded-xl border border-slate-800 bg-slate-950/60 p-3"><div className="grid gap-3 sm:grid-cols-[42px_1.3fr_1fr_1fr_1fr_auto] sm:items-end"><label className="text-xs text-slate-400">Color<input name="badge_color" type="color" value={t.color} onChange={e=>change(t.key,"color",e.target.value)} className="mt-2 h-11 w-11 cursor-pointer rounded-lg border border-slate-700 bg-transparent p-1"/></label><label className="text-xs text-slate-400">Badge name<input name="badge_name" value={t.name} onChange={e=>change(t.key,"name",e.target.value)} className="field mt-2" required/></label><label className="text-xs text-slate-400">From orders<input name="minimum_orders" value={t.min} onChange={e=>change(t.key,"min",e.target.value)} type="number" min="0" className="field mt-2" required/></label><label className="text-xs text-slate-400">To orders<input name="maximum_orders" value={t.max} onChange={e=>change(t.key,"max",e.target.value)} type="number" min="0" placeholder="Unlimited" className="field mt-2"/></label><label className="text-xs text-slate-400">Per order ($)<input name="rate_per_order" value={t.rate} onChange={e=>change(t.key,"rate",e.target.value)} type="number" min="0" step="0.0001" className="field mt-2" required/></label><button type="button" disabled={tiers.length===1} onClick={()=>setTiers(x=>x.filter(row=>row.key!==t.key))} className="mb-1 rounded-lg px-3 py-2 text-slate-500 hover:bg-red-400/10 hover:text-red-300" aria-label={`Remove badge ${index+1}`}>✕</button></div></div>)}</div></div><input className="field" name="notes" placeholder="Version notes (optional)"/><button disabled={p} className="rounded-xl bg-emerald-400 px-4 py-3 font-semibold text-slate-950">{p?"Creating…":"Create badge version"}</button><R s={s}/></form>}
export function DriverCompForm({drivers,schemes,today}:{drivers:O[];schemes:O[];today:string}){const[s,a,p]=useActionState(addDriverCompensation,i);return <form action={a} className="mt-5 grid gap-3 sm:grid-cols-2"><select className="field" name="driver_id">{drivers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input className="field" name="monthly_salary" type="number" min="0" step="0.01" placeholder="Fixed monthly salary" required/><select className="field" name="commission_scheme_id"><option value="">No commission</option>{schemes.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input className="field" name="effective_from" type="date" defaultValue={today}/><input className="field" name="reason" placeholder="Reason (optional)"/><button disabled={p} className="rounded-xl bg-emerald-400 px-4 py-3 font-semibold text-slate-950">{p?"Saving…":"Add compensation change"}</button><div className="sm:col-span-2"><R s={s}/></div></form>}
