import { AppNav } from "@/components/app-nav";
import { createAdminClient } from "@/lib/supabase/admin";
import { dateInTimeZone,getAppSettings } from "@/lib/settings";
import { DriverCompForm,SchemeForm } from "./forms";
export const dynamic="force-dynamic";
export default async function Commission(){
 const settings=await getAppSettings(),s=await createAdminClient();
 const[schemes,versions,tiers,drivers]=await Promise.all([s.from("commission_schemes").select("id,name,is_active").order("name"),s.from("commission_scheme_versions").select("id,commission_scheme_id,version_number,effective_from,effective_to").order("version_number",{ascending:false}),s.from("commission_tiers").select("*").order("minimum_orders"),s.from("drivers").select("id,name,status").eq("status","active").order("name")]);
 const error=schemes.error||versions.error||tiers.error,today=dateInTimeZone(settings.timezone);
 return <main className="min-h-screen bg-slate-950 px-6 py-10 text-slate-100"><div className="mx-auto max-w-7xl"><AppNav current="/payroll"/><h1 className="mt-8 text-4xl font-bold">Driver compensation</h1><p className="mt-3 text-slate-400">Fixed salaries plus badge-based final-tier commission, all effective-dated and versioned.</p>{error&&<p className="mt-6 rounded-xl bg-amber-400/10 p-4 text-amber-200">{error.message}</p>}<div className="mt-8 grid gap-6 xl:grid-cols-[1.35fr_1fr]"><section className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-semibold">New commission badge version</h2><SchemeForm today={today}/></section><section className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-semibold">Change driver compensation</h2><DriverCompForm drivers={drivers.data??[]} schemes={schemes.data??[]} today={today}/></section></div><section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-semibold">Badge version history</h2><div className="mt-5 space-y-4">{(schemes.data??[]).map(sc=><article key={sc.id} className="rounded-xl border border-slate-800 p-4"><h3 className="font-semibold text-emerald-300">{sc.name}</h3>{(versions.data??[]).filter(ver=>ver.commission_scheme_id===sc.id).map(ver=><div key={ver.id} className="mt-4 border-t border-slate-800 pt-4 first:border-0 first:pt-0"><p className="text-sm text-slate-400">Version {ver.version_number} · {ver.effective_from} → {ver.effective_to??"Current"}</p><div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{(tiers.data??[]).filter(t=>t.commission_scheme_version_id===ver.id).map(t=><div key={t.id} className="rounded-xl border border-slate-800 bg-slate-950/60 p-3"><div className="flex items-center gap-2"><span className="h-3 w-3 rounded-full" style={{backgroundColor:t.badge_color??"#94a3b8"}}/><span className="rounded-full border px-2.5 py-1 text-xs font-semibold" style={{color:t.badge_color??"#94a3b8",borderColor:`${t.badge_color??"#94a3b8"}66`,backgroundColor:`${t.badge_color??"#94a3b8"}15`}}>{t.badge_name??"Tier"}</span></div><p className="mt-3 text-sm text-slate-300">{t.minimum_orders}–{t.maximum_orders??"+"} orders</p><p className="mt-1 font-semibold text-emerald-300">${Number(t.rate_per_order).toFixed(2)} / order</p></div>)}</div></div>)}</article>)}</div></section></div></main>
}
